name: omni_qrcode_barcode_web_reader_example
description: "Runnable demo for omni_qrcode_barcode_web_reader."
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  omni_qrcode_barcode_web_reader:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
