name: omni_qrcode_barcode_web_reader
description: "A QrCode and Barcode web reader"
version: 1.1.1
homepage: https://github.com/omnipharma/omni_qrcode_barcode_web_reader.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7
  get: ^4.7.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0

platforms:
  web:

flutter:
  assets:
    - assets/js/scanner.js